### ISSUE TITLE
Recommandation de formatage

### ISSUE THREAD

**Issue by CharlesNepote** [etalab/format-subventions#1]
D'où viennent-elles ? Sont-ce des recommandations qui sont utilisées par d'autres jeux de données spécifiés par Etalab ? Sont-ce les recommandations d'Etalab ? Pour tous les CSV ? Seulement pour ce jeux et pourquoi seulement pour celui-ci ?

En soit j'approuve l'essentiel de ces recommandations mais je pense qu'un effort de mutualisation et d'explicitation est nécessaire. L'explicitation n'a pas forcément besoin d'être faite ici. Vous pourriez par exemple indiquer que les recommandations sont détaillées et explicitées dans "tel document explicitant les recommandations de format préconisées par Etalab".

**Comment by ColinMaudry** [comment]
Ces recommandations sont grandement inspirées du [RFC4180](https://tools.ietf.org/html/rfc4180), qui est ce qui, aujourd'hui, se rapproche le plus d'un "standard" pour le CSV.

Ensuite, il s'agit en partie de choix destinés à limiter les différences structurelles entre les CSV produits par les attribuants.

Ces recommandations sont valables pour les données des subventions, dont la forme a la particularité d'être issue d'un arrêté ministériel. C'est encore chose rare, donc avance encore au cas par cas. Si cette exercice se répète souvent, nous verrons comment mutualiser et harmoniser les pratiques.

Cela répond-il à vos questions ?

**Comment by odtvince** [comment]
Bonjour Charles,
Il ne s'agit pas là de recommandations ou de préconisations d'Etalab, mais pour l'essentiel d'obligations prévues par le texte de l'annexe de l'arrêté du 17 novembre 2017 relatif aux conditions de mises à disposition des données essentielles des conventions de subvention : https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000036040528&categorieLien=id
Ces obligations ne s'appliquent donc qu'à ces jeux de données de subventions.

Il pourrait par ailleurs être intéressant de centraliser quelque part des recommandations ou préconisations fondées sur les meilleures pratiques telles qu'identifiées par les participants de l'ecosystème open-data (dont Etalab), mais il s'agirait d'un exercice différent, à faire en d'autres lieux.
