### ISSUE TITLE
Dans exemple.csv l'expression des pourcentages diffère du principe retenu dans l'arrêté

### ISSUE THREAD

**Issue by loichay** [etalab/format-subventions#3]
Si le séparateur de décimales devient le point pour tout le format : 
- 1 si la subvention n'a qu'un seul bénéficiaire (100%)
- 0.35 si le bénéficiaire reçoit 35% du montant de la subvention

**Comment by ColinMaudry** [comment]
Merci beaucoup @loichay, c'est rectifié dans la version 1.1.1 et 4fa47a66118420a5ccbcd3b1.
